### ISSUE TITLE
Hungary, Slovenia, North Macedonia covid-19 data

### ISSUE THREAD

**Issue by myghf2011** [covid19-eu-zh/covid19-eu-data#31]
Hungary: https://koronavirus.gov.hu/
Slovenia: https://www.gov.si/en/topics/coronavirus-disease-covid-19/
North Macedonia: https://gdi-sk.maps.arcgis.com/apps/opsdashboard/index.html?fbclid=IwAR0Dd9MY7njiNtDkPpPt8R2SeD4pW_6TO12axwKrT4CcegckY4P4Ezt43f4#/2096bd4b051b42948ac3f5747e80c3a5

**Comment by emptymalei** [comment]
Added

1. HU: [Status](https://github.com/covid19-eu-zh/covid19-eu-data/actions?query=workflow%3A%22CI+Download+HU+Data%22)
2. SI: [Status](https://github.com/covid19-eu-zh/covid19-eu-data/actions?query=workflow%3A%22CI+Download+SI+Data%22)

North Macedonia was not added yet since no data table was found. We are not craping ArcGIS at this moment.
